repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files


  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort


  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black


  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies: [ "Flake8-pyproject" ]


  - repo: local
    hooks:
      - id: django-check
        name: Run Django Check
        entry: python manage.py check
        language: system
        pass_filenames: false
        types: [python]
