[project]
name = "{{ cookiecutter.project_slug }}"
version = "0.1.0"
description = ""
authors = [
    {name = "",email = "seu.email@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
{%- if cookiecutter.use_poetry == "yes" %}
dependencies = [
    "Django (==5.2.8)",
    "python-decouple (==3.8)",
    "djangorestframework (==3.16.0)",
    "django-cors-headers (==4.7.0)",
    "gunicorn (==23.0.0)",
    "whitenoise (==6.9.0)",
    "django-db-logger (>=0.1.12)",
{%- if cookiecutter.use_authentication == "yes" %}
    "djangorestframework-simplejwt (==5.5.1)",
{%- endif %}
{%- if cookiecutter.use_documentation == "yes" %}
    "drf-spectacular",
{%- endif %}
{%- if cookiecutter.banco_de_dados == "mysql" %}
    "mysqlclient",
{%- endif %}
{%- if cookiecutter.banco_de_dados == "postgresql" %}
    "psycopg2-binary",
{%- endif %}
]
{%- endif %}

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

{%- if cookiecutter.use_poetry == "yes" %}
[tool.poetry]
package-mode = false

[dependency-groups]
dev = [
    "black (>=23.0.0)",
    "isort (>=5.12.0)",
    "flake8 (>=6.0.0)",
    "flake8-pyproject (>=1.2.0)",
    "django-stubs (>=4.2.0)",
    "pre-commit (==4.3.0)",
{%- if cookiecutter.use_testes == "yes" %}
    "pytest (>=7.0.0)",
    "pytest-cov (>=4.0.0)",
{%- endif %}
    "django-extensions (>=3.2.0)",
    "django-debug-toolbar (>=4.0.0)",
]
{%- endif %}

[tool.black]
line-length = 88
target-version = ['py312']
include = '\.pyi?$'
extend-exclude = '''
/(
  migrations
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88
skip = ["migrations", "venv"]

[tool.django-stubs]
django_settings_module = "core.settings.development"

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203", "W503", "E501"]
exclude = [
    "migrations",
    "__pycache__",
    "manage.py",
    "*/settings/*",
    ".git",
    ".tox",
    "dist",
    "doc",
    "*egg*",
    "build",
    "venv"
]
