[project]
name = "{{ cookiecutter.project_slug }}"
version = "0.1.0"
description = ""
authors = [
    {name = "",email = "email.example@example.com"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
{%- if cookiecutter.use_poetry == "yes" %}
dependencies = [
    "fastapi[standard] (>=0.128.0,<0.129.0)",
    "sqlalchemy[asyncio] (>=2.0.46,<3.0.0)",
    "pydantic-settings (>=2.12.0,<3.0.0)",
    "alembic (>=1.18.1,<2.0.0)",
    "aiosqlite (>=0.22.1,<0.23.0)",
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
{%- endif %}
{%- if cookiecutter.use_poetry == "yes" %}
[tool.poetry]
package-mode = false

[dependency-groups]
dev = [
    "black (>=23.0.0)",
    "isort (>=5.12.0)",
    "flake8 (>=6.0.0)",
    "flake8-pyproject (>=1.2.0)",
    "pre-commit (==4.3.0)",
]
{%- endif %}
